//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalWalletApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int AccountTo { get; set; }
        public Nullable<int> AccountFrom { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> InvoiceNo { get; set; }
        public System.DateTime DatePaid { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual Invoice Invoice { get; set; }
    }
}
