//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Newtonsoft.Json;
namespace DigitalWalletApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkAllocation
    {
        public int TeamID { get; set; }
        public int UserID { get; set; }
        public string Role { get; set; }
        [JsonIgnore]
        public virtual Team Team { get; set; }
        [JsonIgnore]
        public virtual User User { get; set; }
    }
}
